ALTER TABLE users ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE users ADD COLUMN IF NOT EXISTS external_id TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS external_id TEXT;
ALTER TABLE providers ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE providers ADD COLUMN IF NOT EXISTS external_id TEXT;
ALTER TABLE providers ADD COLUMN IF NOT EXISTS config TEXT;
ALTER TABLE boletos ADD COLUMN IF NOT EXISTS external_id TEXT;
ALTER TABLE boletos ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'CREATED';
