name: Deploy Backend Production
on: { workflow_dispatch: {} }
permissions: { id-token: write, contents: read }
jobs:
  deploy:
    uses: ./.github/workflows/deploy-backend.yml
    with: { environment: production }
    permissions: { id-token: write, contents: read }
